### ISSUE TITLE
您用的哪个yolov5版本呀    from torch.cuda import amp ImportError: cannot import name 'amp'

### ISSUE THREAD

**Issue by dbdxnuliba** [mushroom-x/yolov5-simple#2]
python yolov5.py 
Traceback (most recent call last):
  File "yolov5.py", line 21, in <module>
    from models.experimental import attempt_load
  File "/home/dell1804/refer/yolov5-simple-main/models/experimental.py", line 10, in <module>
    from models.common import Conv
  File "/home/dell1804/refer/yolov5-simple-main/models/common.py", line 18, in <module>
    from torch.cuda import amp
ImportError: cannot import name 'amp'

**Comment by dbdxnuliba** [comment]
I have fix it ,use conda install pytorch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0 cudatoolkit=10.2 -c pytorch
